image: atlassian/default-image:3

definitions:
  steps:
  - step: &install-deps
      name: Install Dependencies
      caches:
      - node
      script:
      - npm install

  - step: &run-tests
      name: Run Tests
      script:
      - npm run test

pipelines:
  default:
  - step: *install-deps
  - step: *run-tests

  branches:
    staging:
    - step: *install-deps
    - step: *run-tests
    - step:
      name: Build and Deploy
      script:
      - echo "Building and deploying to staging"
      - npm run build
      - npm run deploy_staging
