image: node:21

definitions:
  steps:
  - step: &install-deps
      name: Install Dependencies
      caches:
      - node
      script:
      - npm install
      artifacts:
      - node_modules/**

  - step: &run-tests
      name: Run Tests
      script:
      - npm run test

  - step: &run-lint
      name: Run Lint
      script:
      - npm run lint

  - step: &deploy-staging
      name: Build and Deploy
      script:
      - echo "Building and deploying to staging"
      - npm run build
      - pipe: atlassian/firebase-deploy:0.2.1
        variables:
          FIREBASE_TOKEN: $FIREBASE_TOKEN
          PROJECT_ID: $FIREBASE_PROJECT
          EXTRA_ARGS: "--only hosting:intuition-writ-of-persona-staging"

  - step: &deploy-production
      name: Build and Deploy
      script:
      - echo "Building and deploying to production (coming soon)"
      - pipe: atlassian/firebase-deploy:0.2.1
        variables:
          FIREBASE_TOKEN: $FIREBASE_TOKEN
          PROJECT_ID: $FIREBASE_PROJECT
          EXTRA_ARGS: "--only hosting:intuition-writ-of-persona"

pipelines:
  branches:
    staging:
    - step: *install-deps
    - step: *run-tests
    - step: *run-lint
    - step: *deploy-staging

    main:
    - step: *install-deps
    - step: *run-tests
    - step: *run-lint
    - step: *deploy-production
