image: atlassian/default-image:3

definitions:
  steps:
  - step: &install-deps
      name: Install Dependencies
      caches:
      - node
      script:
      - npm install

  - step: &run-tests
      name: Run Tests
      script:
      - npm run test

  - step: &run-lint
      name: Run Lint
      script:
      - npm run lint

pipelines:
  branches:
    staging:
    - step: *install-deps
    - step: *run-tests
    - step: *run-lint
    - step:
      name: Build and Deploy
      script:
      - echo "Building and deploying to staging"
      - npm run build
      - npm run deploy_staging

    main:
    - step: *install-deps
    - step: *run-tests
    - step: *run-lint
    - step:
      name: Build and Deploy
      script:
      - echo "Building and deploying to production (coming soon)"
