export interface Spell {
	id: string,
	name: string,
	easy_name: string,
	level: number,
	source: string,
	shape: string,
	cantrip: string,
	cantripcost: number,
	cantripduration: string,
	standard: string,
	standardcost: number,
	standardduration: string,
	empowered: string,
	empoweredcost: number,
	empoweredduration: string,
	save: string,
	potable: boolean,
}