export interface SpellModel {
	id: string,
	name: string,
	easyname: string,
	level: number,
	school: string,
	sources: string,
	shape: string,
	cantrip: string,
	cantripcost: number,
	cantripduration: string,
	standard: string,
	standardcost: number,
	standardduration: string,
	empowered: string,
	empoweredcost: number,
	empoweredduration: string,
	save: string,
	potable: boolean,
	infusable: boolean,
}