export const alchemyRecipesData = [
	{ "desc": "A smelly chewed glob of herb and reagent, applied to the skin.", "effects": "When consumed, Restores 2 Verve.", "id": "f6ae039a", "name": "Stimpaste", "rarity": 1, "reagents": "Vig", "subtype": "Potion", "time": "0m", "type": "recipe" },
	{ "desc": "A Vigour Salve is a small, stinky green paste usually created by chewing the reagents and combining them in a bowl and easing the moisture out until it becomes a smooth salve.", "effects": "When rubbed onto a cut, Restores 5 Verve.", "id": "4cd7a199", "name": "Vigour Paste", "rarity": 1, "reagents": "Vig-Vig", "subtype": "Salve", "time": "30m", "type": "recipe" },
	{ "desc": "Thin metal strands enforce this stoppered glass vial. The red liquid inside bubbles midly, and combusts rapidly when exposed to air.", "effects": "Shatters in a 1sq radius, dealing 4 damage to all engulfed. Flammable items are set alight.", "id": "bbde9101", "name": "Alchemist's Flame", "rarity": 2, "reagents": "Exc-The", "subtype": "Bomb", "time": "30m", "type": "recipe" },
	{ "desc": "Has a distinctive earthy smell when created, which abates as this oily pink liquid matures.", "effects": "When introduced to the bloodstream by mouth or wound, inflicts a WIS and CON Debility, and applies 1 Verve Loss per round for 12 rounds.", "id": "1c34584f", "name": "Bloodboil", "rarity": 4, "reagents": "Exc-Poi-The", "subtype": "Poison", "time": "120m", "type": "recipe" },
	{ "desc": "A thick, consistent yellowing paste that adheres to surfaces and can withstand the motion of a weapon swing.", "effects": "Creates 5 applications of a paste that can be used to adhere other Applicants to weapons.", "id": "096c2823", "name": "Oilstick", "rarity": 1, "reagents": "For-Oil", "subtype": "Applicant", "time": "15m", "type": "recipe" },
	{ "desc": "An oily black substance only distinguished from regular oil by it's thickness when undisturbed, and thinness when worked with.", "effects": "Torches and lamps coated with Torchburn or using torchburn as their fuel burn twice as bright and for four times as long.", "id": "3f6e6aae", "name": "Torchburn", "rarity": 1, "reagents": "Oil-The", "subtype": "Misc", "time": "15m", "type": "recipe" },
];

export const alchemyReagentsData = [
	{ "desc": "Not found in the wild.", "effects": "Water purified through careful manipulation.", "id": "8cdeb555", "name": "Pure Water", "rarity": "Common", "reagents": "Hyd", "subtype": "Chemical", "type": "reagent" },
	{ "desc": "Not found in the wild.", "effects": "Purified alcohol, used to fortify and enhance alchemical recipes.", "id": "a30bd15e", "name": "Pure Alcohol", "rarity": "Common", "reagents": "For", "subtype": "Chemical", "type": "reagent" },
	{ "desc": "Found all across the Civil Holds.", "effects": "Long thin shoots that clumb in large numbers. Older shoots die at the base, and can be collected and crushed into flakes. Grows in grassy areas.", "id": "787d3e3e", "name": "Starkth Nettle", "rarity": "Common", "reagents": "The", "subtype": "Flora", "type": "reagent" },
	{ "desc": "Found in the East of the Civil Holds.", "effects": "A shrub with long green and grey ferrugated leaves. Its sap is thin and lightly tacky.", "id": "7cb0ab0c", "name": "Eastern Silverbarb", "rarity": "Common", "reagents": "Vig", "subtype": "Flora", "type": "reagent" },
	{ "desc": "Found in the West of the Civil Holds.", "effects": "A shrub with long green and grey ferrugated leaves. Its sap is thick and tacky. Grows commonly in the West of the Civil Holds.", "id": "1330357f", "name": "Western Silverbarb", "rarity": "Common", "reagents": "Exc", "subtype": "Flora", "type": "reagent" },
	{ "desc": "Found in central Civil Holds.", "effects": "A small grass that grows in dryer climates. Has a sickly yellow-green colour and the leaves always appear dry.", "id": "ad7d143c", "name": "Gillyweed", "rarity": "Common", "reagents": "Con", "subtype": "Flora", "type": "reagent" },
	{ "desc": "Found in the South of the Civil Holds.", "effects": "A medium sized bush whose rich green leaves can be dried into a slightly sweet, soothing tea. Grows in temperate, hilly areas.", "id": "55f2e24e", "name": "Palomile", "rarity": "Common", "reagents": "Soo", "subtype": "Flora", "type": "reagent" },
	{ "desc": "Found in the central West and outer East of the Civil Holds.", "effects": "Also called Dryad's Guide, lunestalk is a small leafy grass with a large stalk which smells and tastes terrible, but which blooms twice per year. Grows in grass and woodlands.", "id": "0eb71426", "name": "Lunestalk", "rarity": "Common", "reagents": "Oil", "subtype": "Flora", "type": "reagent" },
	{ "desc": "Found in central and South Civil Holds.", "effects": "The lure of the bright red berries of this bush is dangerous, as ingestion usually incites vomiting shortly after. Grows in temperate climates.", "id": "5e2c2152", "name": "Kahinder", "rarity": "Common", "reagents": "Cor", "subtype": "Flora", "type": "reagent" },
	{ "desc": "Found all across the Civil Holds.", "effects": "A medium sized tree. The underside of the leaves have a waxen protective coating which can be scraped off. Grows commonly.", "id": "115c1ee8", "name": "Sourleaf", "rarity": "Common", "reagents": "Poi", "subtype": "Flora", "type": "reagent" },
	{ "desc": "Found all across the Civil Holds, in wet areas.", "effects": "A wilted grass with fungi-like mushroom tips which have purple and yellow splotches on the underside. When the tip is broken, emits a neutral scent that travels far.", "id": "542b3b1a", "name": "Hethweed", "rarity": "Common", "reagents": "Sce", "subtype": "Flora", "type": "reagent" },
	{ "desc": "Found all across the Civil Holds, in wet areas.","effects":"A small green shoot that is tasty and grinds into a paste easily.","id":"dd80582b","name":"Lunestalk","rarity":"Uncommon","reagents":"Vig-For-Hyd","subtype":"Flora","type":"reagent"}
]