import { Outlet } from "react-router";

function Account() {
	return (
		<>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>

			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>

			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>

			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
			<div>Account</div>
		</>
	)
}

export default Account
